hospital:
  code: "10989"
  name: "รพช. หัวตะพาน"
  token: "11|hbkDX13O14cY7j4Jz6BTDz5iTtvFnNvfYeA8rOL8ede50d0b"
  server_url: "http://127.0.0.1/aopod"
  bed_qty: 30

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "rims"
  password: "h10989"
  database: "hosxe"

schedule:
  opd_cron: "0 */2 * * *"
  ipd_cron: "0 */2 * * *"
  bed_cron: "*/15 * * * *"
  sync_days_back: 10
  chunk_size: 200

web:
  port: 8989
  open_browser: true
